### ISSUE TITLE
Multiple-tokens mode?

### ISSUE THREAD

**Issue by LEW21** [tlodderstedt/oauth2#26]
Hi,

I'm wondering what happened to the multiple-tokens mode described in https://www.ietf.org/mail-archive/web/oauth/current/msg03639.html

It's missing from the draft in this repo, and from https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-07. However, it sounds much easier to use for clients, and is much faster, than sending multiple requests. Why was it abandoned?

**Comment by tlodderstedt** [comment]
Hi,

the working group didn't support the idea at that time. I have learned that the same results can be achieved by issuing a refresh token and use that to obtain different access tokens. We have done that in real implementations.
