### ISSUE TITLE
rework text on implicit and co

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#38]
Nat made a proposal, Filip and Vittorio suggested to explicitly list all affected response types 
wait for Daniel's analysis 
send new proposal to list
SHOULD NOT or MUST NOT?
publish new revision

**Comment by webhamster** [comment]
In cleaned up the proposal from the mailing list (but I don't see Filip's or Vittorio's comments):


> In order to avoid these issues, clients MUST NOT use the implicit
> grant or return access tokens in the authorization response
> unless the issued access tokens are sender-constrained and access
> token injection at the client is prevented. (Note that use of the
> state parameter is not sufficient to provide access token
> injection.) 

I would be fine with this text.

**Comment by tlodderstedt** [comment]
I likes Nat's generic proposal and would like to build on it. What about this: 

In order to avoid these issues, clients SHOULD NOT use response types issuing access tokens in the authorization response unless the particular response type detects access token injection and the issued access tokens are sender-constrained. The following response types do not fulfill this requirement: "token", "token id_token" and "code token id_token".

**Comment by tlodderstedt** [comment]
and not to forget

(Note that use of the
state parameter is not sufficient to provide access token
injection.)

**Comment by tlodderstedt** [comment]
> In order to avoid these issues, clients MUST NOT use the implicit
> grant (response type "token") or any other response type issuing access tokens in the 
> authorization response, such as "token id_token" and "code token id_token", unless the issued access tokens are sender-constrained and access token injection at the client is prevented. 

> (Note that use of the state parameter is not sufficient to provide access token
> injection.)

**Comment by webhamster** [comment]
Getting closer :-) 
Small changes (highlighted):


> In order to avoid these issues, clients MUST NOT use the implicit
> grant (response type "token") or any other response type issuing access tokens in the
> authorization response, such as "token id_token" and "code token id_token", unless the issued access tokens are sender-constrained **to the respective client** and access token injection **at the client** is prevented.
> (Note that use of the state parameter is not sufficient to provide access token injection.)

**Comment by tlodderstedt** [comment]
"to the respective client" sagen wir nirgendwo sonst so spezifisch, warum hier?

**Comment by webhamster** [comment]
An access token bound to the browser and used by an SPA might be considered "sender-constrained", but it is not bound to the client. We should highlight that a binding to the **client** is important (not to the IP network, not to anything else...).

**Comment by tlodderstedt** [comment]
response type "code token" nicht vergessen

**Comment by tlodderstedt** [comment]
A sender constrained access token scopes the applicability of an access token to a certain sender.  This sender is
obliged to demonstrate knowledge of a certain secret as prerequisite for the acceptance of that token at the recipient (e.g. a resource server).
