### ISSUE TITLE
Use PKCE instead of State for CSRF protection

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#39]
Advantages: 
* security check at the AS
* reduces number of values the client needs to keep for a transaction (state+verifier -> verifier)

**Comment by tlodderstedt** [comment]
Rückfrage an Uni Stuttgart läuft, ggf. wird ursprüngliche Beweis für OAuth angepasst

**Comment by tlodderstedt** [comment]
waiting for WG Chairs and WG Consensus

**Comment by webhamster** [comment]
Proposal for text:

> If PKCE [@RFC7636] is used by the client and the authorization server supports PKCE, clients MAY opt to not use `state` for protection against Cross-Site Request Forgery, as such protection is provided by PKCE. In this case, `state` MAY be used again for its original purpose, namely transporting data about the application state of the client.
> 
> It is important to note that:
> 
>  1. If `state` is used for carrying application state, and integrity of its contents is a concern, clients MUST protect `state` against tampering and swapping. This can be achieved by binding the contents of `state` to the browser session and/or signed/encrypted state values [@I-D.bradley-oauth-jwt-encoded-state].
>  2. There is no defined mechanism for clients to detect whether an authorization server supports PKCE or not. Clients that use PKCE despite the authorization server not supporting it will not receive any indication of the lack of support for PKCE. If the authorization server does not support PKCE, `state` MUST be used for CSRF protection.

**Comment by webhamster** [comment]
We might want to use that text for the WG call.

**Comment by danielfett** [comment]
Text added.
