### ISSUE TITLE
text on client authentication

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#42]

**Comment by tlodderstedt** [comment]
shall we include recommendations on client authentication into the BCP?

**Comment by tlodderstedt** [comment]
use public key crypto instead of shared secrets - private_key_jwt, mtls

**Comment by tlodderstedt** [comment]
motivation: client credentials phishing, management and attack vectors at AS

**Comment by tlodderstedt** [comment]
waiting for WG Chairs and WG Consensus

**Comment by danielfett** [comment]
Text merged:

> It is RECOMMENDED to use asymmetric (public key based) methods for client authentication such as MTLS [I-D.draft-ietf-oauth-mtls] or private_key_jwt [OIDC]. In comparison to client authentication with shared secrets, these methods are more robust against a number of attacks, for example if an authorization server becomes compromised.
