### ISSUE TITLE
"It is also recommended to use end-to-end TLS whenever possible."

### ISSUE THREAD

**Issue by danielfett** [tlodderstedt/oauth2#47]
In this sentence (Section "Token Replay Prevention"), it is not clear whether this is just a recommendation for TLS (in this case, the recommendation should be changed into a MUST), or if the focus is on "end-to-end", which then should be explained, e.g., "i.e., TLS connections should not be terminated, for example, at ingress proxies".

**Comment by danielfett** [comment]
@tlodderstedt Your opinion? Was this meant to discourage TLS termination at ingress proxies?

**Comment by tlodderstedt** [comment]
It's more an inspiration to think twice :-). 

It shall convey "if you can avoid terminating TLS at a proxy, do so. It simplifies your life." Handling of proxies is explained in Section 4.11. Probably we should a statement like "If the TLS traffic is terminated at an intermediary, please consider Section 4.11"
