### ISSUE TITLE
Table of Content w/ links

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#49]

**Comment by webhamster** [comment]
This seems to be a generic problem with the xml2rfc toolchain and long section titles; see for example https://tools.ietf.org/html/rfc6819 (TOC - Section 4.1.4) and https://tools.ietf.org/html/rfc7636 (TOC - Section 4.3).
Our toolchain seems to work fine, therefore I am closing this bug.

**Comment by tlodderstedt** [comment]
you mean w/ xml2rfc v3? I‘m asking the problem disappeared after we moved back to v2.

**Comment by webhamster** [comment]
Yes, the problem disappeared with moving back to v2. I think the move to v3 is not something we will consider for this document (due to missing acceptance at the IETF).
