### ISSUE TITLE
Double recommendation for PKCE and (PKCE or Client Auth)? 

### ISSUE THREAD

**Issue by webhamster** [tlodderstedt/oauth2#50]
We are currently recommending PKCE for all clients/AS, and then say that AS must enforce PKCE or client authentication.

> Clients utilizing the authorization grant type MUST use PKCE [@!RFC7636] in order to (with the help of the authorization server) detect and prevent attempts to inject (replay) authorization codes into the authorization response. The PKCE challenges must be transaction-specific and securely bound to the user agent in which the transaction was started. OpenID Connect clients MAY use the nonce parameter of the OpenID Connect authentication request as specified in [@!OpenID] in conjunction with the corresponding ID Token claim for the same purpose.
> 
> Note: although PKCE so far was recommended as a mechanism to protect native apps, this advice applies to all kinds of OAuth clients, including web applications.
> 
> Authorization servers MUST bind authorization codes to a certain client and authenticate it using an appropriate mechanism (e.g. client credentials or PKCE).

I think we can just remove the last sentence, what do you think?

**Comment by ve7jtb** [comment]
I agree the last sentance is redundant.
