### ISSUE TITLE
Discourage use of Resource Owner Password Credentials Grant Type

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#52]
waiting for WG Chairs and WG Consensus

**Comment by webhamster** [comment]
Text proposal:

> The resource owner password credentials grant MUST NOT be used. The main issue of this grant type is that it insecurely exposes the credentials of the resource owner to the client. As a secondary issue, it is not easily adaptable to two-factor authentication, authentication with cryptographic credentials (WebCrypto, WebAuthn, U2F), and authentication processes that require multiple steps.

**Comment by danielfett** [comment]
Merged text.
