### ISSUE TITLE
PKCE is currently optional for AS - can be ignored!

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#53]

**Comment by webhamster** [comment]
See also text proposed for Issue #39.

**Comment by danielfett** [comment]
Improve text:
AS must either (a) publish, in its AS metadata (RFC8418), the element `code_challenge_methods_supported` containing the supported PKCE challenge methods (then the client can rely on the AS supporting PKCE) or (b) there must be a deployment-specific way to determine PKCE support by the AS.

**Comment by danielfett** [comment]
I suggest to make this a SHOULD instead, and will add it to the spec accordingly. Reasons: With a MUST, we force ASs to either implement RFC8418 or to invent some new way of detecting PKCE support (which is not a good thing, standards-wise). So effectively, we force RFC8418 upon everybody...?

**Comment by tlodderstedt** [comment]
we should :-)
