### ISSUE TITLE
Potential Mix-Up between user and client ids

### ISSUE THREAD

**Issue by tlodderstedt** [tlodderstedt/oauth2#55]
Neil Madden proposed the following text:
---
4.x Client Impersonation of Resource Owner

Resource servers may make access control decisions based on the identity of the resource owner as communicated in the "sub" claim returned by the authorization server in a token introspection response [RFC 7662] or other mechanism. If a client is able to choose its own client_id during registration with the authorization server, then there is a risk that it can register with the same "sub" value as a privileged user. A subsequent access token obtained under the client_credentials grant may be mistaken as an access token authorized by the privileged user if the resource server does not perform additional checks.

4.1.x Proposed Countermeasures

Authorization servers SHOULD NOT allow clients to influence their client_id or "sub" value or any other claim that might cause confusion with a genuine resource owner. Where this cannot be avoided, authorization servers MUST provide another means for the resource server to distinguish between access tokens authorized by a resource owner from access tokens authorized by the client itself.

**Comment by danielfett** [comment]
Added to the draft!
